export default {
    GET_TESTS: "GET_TESTS",
    GET_TESTS_FULFILLED: "GET_TESTS_FULFILLED",
    GET_TEST: "GET_TEST",
    GET_TEST_FULFILLED: "GET_TEST_FULFILLED",
    POST_TEST: "POST_TEST",
    POST_TEST_FULFILLED: "POST_TEST_FULFILLED",
    PATCH_TEST: "PATCH_TEST",
    PATCH_TEST_FULFILLED: "PATCH_TEST_FULFILLED",
    GET_TEST_RESULTS: "GET_TEST_RESULTS",
    GET_TEST_RESULTS_FULFILLED: "GET_TEST_RESULTS_FULFILLED",
    POST_TEST_RESULTS: "POST_TEST_RESULTS",
    POST_TEST_RESULTS_FULFILLED: "POST_TEST_RESULTS_FULFILLED"
};
