export default {
    GET_TESTS: "GET_TESTS",
    GET_TESTS_FULFILLED: "GET_TESTS_FULFILLED",
    GET_TEST: "GET_TEST",
    GET_TEST_FULFILLED: "GET_TEST_FULFILLED",
    POST_TEST: "POST_TEST",
    POST_TEST_FULFILLED: "POST_TEST_FULFILLED",
    PATCH_TEST: "PATCH_TEST",
    PATCH_TEST_FULFILLED: "PATCH_TEST_FULFILLED",
    DELETE_TEST: "DELETE_TEST",
    DELETE_TEST_FULFILLED: "DELETE_TEST_FULFILLED",
    RESET_TEST: "RESET_TEST"
};
