export default {
    GET_SUBJECTS: 'GET_SUBJECTS',
    GET_SUBJECTS_FULFILLED: 'GET_SUBJECTS_FULFILLED',
    GET_SUBJECT: 'GET_SUBJECT',
    GET_SUBJECT_FULFILLED: 'GET_SUBJECT_FULFILLED',
    POST_SUBJECT: 'POST_SUBJECT',
    POST_SUBJECT_FULFILLED: 'POST_SUBJECT_FULFILLED',
    PUT_SUBJECT: 'PUT_SUBJECT',
    PUT_SUBJECT_FULFILLED: 'PUT_SUBJECT_FULFILLED'
};
