export default {
    GET_SUBJECTS: "GET_SUBJECTS",
    GET_SUBJECTS_FULFILLED: "GET_SUBJECTS_FULFILLED",
    GET_SUBJECT: "GET_SUBJECT",
    GET_SUBJECT_FULFILLED: "GET_SUBJECT_FULFILLED",
    POST_SUBJECT: "POST_SUBJECT",
    POST_SUBJECT_FULFILLED: "POST_SUBJECT_FULFILLED",
    PATCH_SUBJECT: "PATCH_SUBJECT",
    PATCH_SUBJECT_FULFILLED: "PATCH_SUBJECT_FULFILLED",
    DELETE_SUBJECT: "DELETE_SUBJECT",
    DELETE_SUBJECT_FULFILLED: "DELETE_SUBJECT_FULFILLED",
    RESET_SUBJECT: "RESET_SUBJECT"
};
