export default {
    GET_CLASSES: 'GET_CLASSES',
    GET_CLASSES_FULFILLED: 'GET_CLASSES_FULFILLED',
    GET_CLASS: 'GET_CLASS',
    GET_CLASS_FULFILLED: 'GET_CLASS_FULFILLED',
    POST_CLASS: 'POST_CLASS',
    POST_CLASS_FULFILLED: 'POST_CLASS_FULFILLED',
    PUT_CLASS: 'PUT_CLASS',
    PUT_CLASS_FULFILLED: 'PUT_CLASS_FULFILLED'
};
