export default {
    GET_CLASSES: "GET_CLASSES",
    GET_CLASSES_FULFILLED: "GET_CLASSES_FULFILLED",
    GET_CLASS: "GET_CLASS",
    GET_CLASS_FULFILLED: "GET_CLASS_FULFILLED",
    POST_CLASS: "POST_CLASS",
    POST_CLASS_FULFILLED: "POST_CLASS_FULFILLED",
    PATCH_CLASS: "PATCH_CLASS",
    PATCH_CLASS_FULFILLED: "PATCH_CLASS_FULFILLED",
    PATCH_PUPILS_ENROLMENT: "PATCH_PUPILS_ENROLMENT",
    PATCH_PUPILS_ENROLMENT_FULFILLED: "PATCH_PUPILS_ENROLMENT_FULFILLED"
};
