export default {
    LOGIN: "LOGIN",
    LOGIN_FULFILLED: "LOGIN_FULFILLED",
    GET_PROFILE: "GET_PROFILE",
    GET_PROFILE_FULFILLED: "GET_PROFILE_FULFILLED",
    GET_USER: "GET_USER",
    GET_USER_FULFILLED: "GET_USER_FULFILLED",
    GET_USERS: "GET_USERS",
    GET_USERS_FULFILLED: "GET_USERS_FULFILLED",
    POST_USER: "POST_USER",
    POST_USER_FULFILLED: "POST_USER_FULFILLED",
    PUT_USER: "PUT_USER",
    PUT_USER_FULFILLED: "PUT_USER_FULFILLED",
    DELETE_USER: "DELETE_USER",
    DELETE_USER_FULFILLED: "DELETE_USER_FULFILLED"
};
